# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9b1d2eabd331256f6b7713066ddeeaf0d6309015f45042ec1f9a4b2d71df252acd8f455343f1feb16a06dbcc3ccf6c32e0bfe77684ab486d40e4a7bc31d5e0

test:
  secret_key_base: 6684c81ca31405bb14c747aaeb5c9515445b66e03d229796f2f051d5a8f6c842bac785ad898a43a17bac4453ce3b85148739acb961f7de1bfd5a47c1cbe455d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
